api/urls.py
from django.urls import path
from api.views import *

app_name = "api"


urlpatterns = [
    path('sale_products/', SaleProductsViewSet.as_view(), name='sale_products'),
    path('new_products/', NewProductsViewSet.as_view(), name='new_products'),
    path('product/<int:pk>', ProductViewSet.as_view(), name='product'),
    path('categories/', CategoriesViewSet.as_view(), name='categories'),
    path('categories/<int:pk>', CategoriesProductViewSet.as_view(), name='categories_products'),
    path('order/create', CreateOrderViewSet.as_view(), name='create_order'),
    # path('order/<int:pk>', OrderViewSet.as_view(), name='order'),
    path('order/<int:id>/<int:pk>', OrderViewSet.as_view(), name='order'),
    # path('orders/', OrdersViewSet.as_view(), name='orders'),
    path('orders/<int:id>', OrdersViewSet.as_view(), name='orders'),
    path('reviews/<int:pk>', ReviewViewSet.as_view(), name='reviews'),
    # path('profile/me', ProfileViewSet.as_view(), name='profile'),
    path('profile/<int:id>', ProfileViewSet.as_view(), name='profile'),
    # path('cart/', CartViewSet.as_view(), name='cart'),
    path('cart/<int:id>', CartViewSet.as_view(), name='cart'),
    # path('cart/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/<int:id>/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/add', CartItemAddViewSet.as_view(), name='cart_item_add'),
    path('profile/create', ProfileCreateViewSet.as_view(), name='profile_create'),
    path('fcm/delete/<int:pk>', DeleteDeviceToken.as_view(), name='device_delete'),

    path('auth', AuthViewSet.as_view(), name='auth'),
]

cart/urls.py
from django.urls import path
from .views import *


app_name = "cart"


urlpatterns = [
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

orders/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = "orders"


urlpatterns = [
    path('create/', order_create, name='order_create'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "products"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('product/<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('category/<slug:slug>', category_detail, name='category_detail'),
    path('add_review/<int:id>', add_review, name='add_review'),
    path('selection/new', selection_new, name='selection_new'),
    path('selection/sale', selection_sale, name='selection_sale'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.functional import curry
from django.views.defaults import permission_denied, page_not_found, server_error

handler403 = curry(permission_denied, exception=Exception('Permission Denied'), template_name='products/errors/403.html')
handler404 = curry(page_not_found, exception=Exception('Page not Found'), template_name='products/errors/404.html')
handler500 = curry(server_error, template_name='products/errors/500.html')


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('products.urls', namespace='products')),
    path('', include('account.urls', namespace='account')),
    path('', include('static_pages.urls', namespace='static_pages')),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('tinymce/', include('tinymce.urls')),
    path('fcm/', include('fcm.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('403', handler403),
        path('404', handler404),
        path('500', handler500),
    ]

cart/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save, post_delete
from django.dispatch import receiver

from products.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    total = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='Всего')

    def __str__(self):
        return self.user.username + 'cart'

    def get_total(self):
        return sum(item.get_cost() for item in self.items.all())

    class Meta:
        verbose_name_plural = 'Корзины'
        verbose_name = 'Корзина'


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items', verbose_name='Корзина №')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name='Сумма')

    def __str__(self):
        return '{}'.format(self.cart.id)

    def get_cost(self):
        return self.product.get_price() * self.quantity


@receiver(pre_save, sender=CartItems)
def update_cart(sender, instance, **kwargs):
    instance.price = instance.get_cost()


@receiver(post_save, sender=CartItems)
@receiver(post_delete, sender=CartItems)
def update_total(sender, instance, **kwargs):
    instance.cart.total = instance.cart.get_total()
    instance.cart.save()

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    data = {}
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        data['success'] = True
    data['amount'] = cart.__len__()
    return JsonResponse(data)


def cart_remove(request, product_id):
    cart = Cart(request)
    data = {}
    product = get_object_or_404(Product, id=product_id)
    if cart.remove(product):
        data['success'] = True
        data['amount'] = cart.__len__()
    return JsonResponse(data)


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    context = {
        'cart': cart,
    }
    return render(request, 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends "products/_base.html" %}

{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content %}
    <div class="inner-header">
        <h1>Корзина товаров</h1>
        <div class="breadcrumbs text-center">
            <a href="{% url 'products:main_page' %}">Главная</a>
            <span>  /  </span>
            <span>Корзина</span>
        </div>
    </div>
    <section class="shopping-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Ваши товары</h2>
                    {% if cart|length > 0 %}
                        <div class="table-responsive-sm">
                            <table>
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th class="text-center">Продукт</th>
                                        <th class="text-center">Цена</th>
                                        <th class="text-center">Количество</th>
                                        <th class="text-center">Сумма</th>
                                        <th class="text-center">Удалить</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                    {% with product=item.product %}
                                    <tr class="tr_item">
                                        <td class="td-img">
                                            <img src="{{ product.image.url }}" alt="{{ product.name }}" />
                                        </td>
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                        </td>
                                        <td class="num">{{ item.price }} руб.</td>
                                        <td>
                                            <form action="{% url "cart:cart_add" product.id %}" method="post" class="add" data-id="{{ product.id }}">
                                                <div class="numbers-row">
                                                    {% csrf_token %}
                                                    <span class="change dec">-</span>
                                                    {{ item.update_quantity_form.quantity }}
                                                    <span class="change inc">+</span>
                                                </div>
                                                {{ item.update_quantity_form.update }}
                                            </form>
                                        </td>
                                        <td class="num sum_for_item"><span id="sum_for_item_{{ product.id }}">{{ item.total_price }} руб.</span></td>
                                        <td>
                                            <a href="{% url "cart:cart_remove" product.id %}" id="delete-item2" data-id="{{ product.id }}">
                                                <span class="red">
                                                    <i class="fa fa-close" style="font-size:24px"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endwith %}
                                    {% endfor %}
                                    <tr class="total">
                                        <td class="total_num">Всего</td>
                                        <td class="total_num" colspan="4"></td>
                                        <td class="total_num num">{{ cart.get_total_price }} руб.</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <h4 class="text-center">В корзине нет товаров</h4>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-6">
                     <a href="{% url "products:main_page"%}" class="add-to-cart2">Продолжить покупки</a>
                </div>
                {% if cart|length > 0 %}
                <div class="col-sm-6 col-md-6 order-btn">
                    <a href="{% url "orders:order_create" %}" class="add-to-cart2">Оформить заказ</a>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('.change').on('click', function() {
                var par_form = $(this).closest('form');
                var id = par_form.data('id');
                var quantity = parseInt(par_form.find('#id_quantity').val());
                if ($(this).hasClass('dec')){
                     quantity -= 1;
                } else if ($(this).hasClass('inc')){
                    quantity += 1;
                }
                var url = par_form.attr('action');
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        quantity: quantity,
                        update: true,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (data) {
                        if (data.success) {
                            $('#total-in-cart').text(data.amount);
                            $('#basket').load(' .basket-items');
                            $('.total').load(' .total_num');
                            par_form.closest('.tr_item').find('.sum_for_item').load(' #sum_for_item_' + id);
                        }
                    }
                });
            });
        });
        $(document).on('click', '#delete-item2', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var url = $(this).attr('href');
            $.ajax({
                type: 'GET',
                url: url,
                data: {
                    product_id: id
                },
                success: function (data) {
                    if (data.success) {
                        document.location.reload(true);
                    }
                }
            });
        });
    </script>
{% endblock %}