api/urls.py
from django.urls import path
from api.views import *

app_name = "api"


urlpatterns = [
    path('sale_products/', SaleProductsViewSet.as_view(), name='sale_products'),
    path('new_products/', NewProductsViewSet.as_view(), name='new_products'),
    path('product/<int:pk>', ProductViewSet.as_view(), name='product'),
    path('categories/', CategoriesViewSet.as_view(), name='categories'),
    path('categories/<int:pk>', CategoriesProductViewSet.as_view(), name='categories_products'),
    path('order/create', CreateOrderViewSet.as_view(), name='create_order'),
    # path('order/<int:pk>', OrderViewSet.as_view(), name='order'),
    path('order/<int:id>/<int:pk>', OrderViewSet.as_view(), name='order'),
    # path('orders/', OrdersViewSet.as_view(), name='orders'),
    path('orders/<int:id>', OrdersViewSet.as_view(), name='orders'),
    path('reviews/<int:pk>', ReviewViewSet.as_view(), name='reviews'),
    # path('profile/me', ProfileViewSet.as_view(), name='profile'),
    path('profile/<int:id>', ProfileViewSet.as_view(), name='profile'),
    # path('cart/', CartViewSet.as_view(), name='cart'),
    path('cart/<int:id>', CartViewSet.as_view(), name='cart'),
    # path('cart/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/<int:id>/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/add', CartItemAddViewSet.as_view(), name='cart_item_add'),
    path('profile/create', ProfileCreateViewSet.as_view(), name='profile_create'),
    path('fcm/delete/<int:pk>', DeleteDeviceToken.as_view(), name='device_delete'),

    path('auth', AuthViewSet.as_view(), name='auth'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "products"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('product/<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('category/<slug:slug>', category_detail, name='category_detail'),
    path('add_review/<int:id>', add_review, name='add_review'),
    path('selection/new', selection_new, name='selection_new'),
    path('selection/sale', selection_sale, name='selection_sale'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.functional import curry
from django.views.defaults import permission_denied, page_not_found, server_error

handler403 = curry(permission_denied, exception=Exception('Permission Denied'), template_name='products/errors/403.html')
handler404 = curry(page_not_found, exception=Exception('Page not Found'), template_name='products/errors/404.html')
handler500 = curry(server_error, template_name='products/errors/500.html')


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('products.urls', namespace='products')),
    path('', include('account.urls', namespace='account')),
    path('', include('static_pages.urls', namespace='static_pages')),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('tinymce/', include('tinymce.urls')),
    path('fcm/', include('fcm.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('403', handler403),
        path('404', handler404),
        path('500', handler500),
    ]

static_pages/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "static_pages"

urlpatterns = [
    path('contacts/', contacts_view, name='contacts_view'),
    path('add_question/', add_question_view, name='add_question_view'),
    path('about/', about_page, name='about_page'),
    path('delivery/', delivery_page, name='delivery_page'),
    path('policy/', policy_page, name='policy_page'),
]

orders/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from fcm.utils import get_device_model
from pyfcm import FCMNotification

from products.models import Product
from project import settings


class Status(models.Model):
    name = models.CharField(verbose_name='Статус', max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Order(models.Model):
    # PAY_CHOICES = (
    #     ('Кредитной картой', 'Кредитной картой'),
    #     ('Наличными', 'Наличными')
    # )

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, default='',
                             blank=True, null=True)
    first_name = models.CharField(verbose_name='Имя', max_length=50)
    last_name = models.CharField(verbose_name='Фамилия', max_length=50, blank=True, default='')
    phone_number = models.CharField(verbose_name='Телефон', max_length=20)
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(verbose_name='Адрес', max_length=250, blank=True)
    comment = models.TextField(verbose_name='Комментарий', default='', blank=True)
    # pay_method = models.CharField(verbose_name='Способ оплаты', max_length=20, default='', choices=PAY_CHOICES)
    pay_method = models.CharField(verbose_name='Способ оплаты', max_length=20, default='Наличными', blank=True)
    status = models.ForeignKey(Status, verbose_name='Статус заказа', on_delete=models.CASCADE, default='')
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)
    total_price = models.DecimalField(verbose_name='Сумма', max_digits=10, decimal_places=2, blank=True, null=True)
    # __original_mode = 'Новый'

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    # def __init__(self, *args, **kwargs):
    #     super(Order, self).__init__(*args, **kwargs)
    #     self.__original_mode = self.status

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    # def save(self, force_insert=False, force_update=False, *args, **kwargs):
    #     if self.status != self.__original_mode:
    #         change_status(self.status, self.id, self.user_id)
    #
    #     super(Order, self).save(force_insert, force_update, *args, **kwargs)
    #     self.__original_mode = self.status


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2, blank=True, null=True)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)
    total_price = models.DecimalField(verbose_name='Сумма', max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


@receiver(pre_save, sender=OrderItem)
def set_price_to_item(sender, instance, **kwargs):
    instance.price = instance.product.get_price()
    instance.total_price = instance.get_cost()


@receiver(post_save, sender=OrderItem)
def set_total_price_to_order(sender, instance, **kwargs):
    instance.order.total_price = instance.order.get_total_cost()
    instance.order.save()


# def change_status(new_status, order_id, user_id):
@receiver(pre_save, sender=Order)
def change_status(sender, instance, **kwargs):
    try:
        order = Order.objects.get(id=instance.id)
    except Order.DoesNotExist:
        order = None
    if order is not None:
        if instance.status != order.status:
            server_key = settings.FCM_APIKEY
            message_title = "Заказ №" + str(instance.id)
            message_body = "Статус заказа изменен на: " + str(instance.status)
            device = get_device_model()
            try:
                my_phone = device.objects.get(dev_id=instance.user_id)
                reg_id = my_phone.reg_id
                FCMNotification(api_key=server_key).notify_single_device(registration_id=reg_id,
                                                                         message_title=message_title,
                                                                         message_body=message_body)
            except device.DoesNotExist:
                pass

    # FCMNotification(api_key=server_key).notify_single_device(registration_id=reg_id2, message_body=message_body, data_message=data_message)

static_pages/models.py
from django.db import models
from tinymce.models import HTMLField


class Contacts(models.Model):
    email = models.EmailField(verbose_name='Email')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address = models.CharField(max_length=256, verbose_name='Адрес')
    content = HTMLField(verbose_name='Краткое описание')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    title = models.CharField(max_length=255, null=True, blank=True, default=None)
    keywords = models.CharField(max_length=255, null=True, blank=True, default=None)
    description_seo = models.TextField(null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'


class Question(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(verbose_name='Email')
    question = models.TextField(verbose_name='Вопрос')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class About(models.Model):
    content = HTMLField(verbose_name='Текст страницы')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    title = models.CharField(max_length=255, null=True, blank=True, default=None)
    keywords = models.CharField(max_length=255, null=True, blank=True, default=None)
    description_seo = models.TextField(null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Страница о нас'
        verbose_name_plural = 'Страница о нас'


class Delivery(models.Model):
    content = HTMLField(verbose_name='Текст страницы')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    title = models.CharField(max_length=255, null=True, blank=True, default=None)
    keywords = models.CharField(max_length=255, null=True, blank=True, default=None)
    description_seo = models.TextField(null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Страница доставка и оплата'
        verbose_name_plural = 'Страница доставка и оплата'


class Policy(models.Model):
    content = HTMLField(verbose_name='Текст страницы')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Политика конфеденциальности'
        verbose_name_plural = 'Политика конфеденциальности'

static_pages/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['created']

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_method = 'post'
    #     self.helper.wrapper_class = 'row'
    #     self.helper.label_class = 'col-lg-4'
    #     self.helper.field_class = 'col-lg-8'
    #     self.helper.add_input(Submit('submit', 'Отправить', css_class='add-to-cart2'))

static_pages/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from products.models import Category
from static_pages.forms import QuestionForm
from static_pages.models import Contacts, About, Delivery, Policy


def contacts_view(request):
    contacts = Contacts.objects.latest('id')
    categories = Category.objects.filter(is_active=True)
    form = QuestionForm()
    context = {
        'contacts': contacts,
        'categories': categories,
        'form': form,
    }
    return render(request, 'static_pages/contacts.html', context)


def add_question_view(request):
    contacts = Contacts.objects.latest('id')
    categories = Category.objects.filter(is_active=True)
    form = QuestionForm(request.POST)
    context = {
        'contacts': contacts,
        'categories': categories,
    }
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    else:
        context['form'] = form
        return render(request, 'static_pages/contacts.html', context)


def about_page(request):
    content = About.objects.latest('id')
    categories = Category.objects.filter(is_active=True)
    return render(request, 'static_pages/about.html', {'content': content, 'categories': categories, })


def delivery_page(request):
    content = Delivery.objects.latest('id')
    categories = Category.objects.filter(is_active=True)
    return render(request, 'static_pages/delivery.html', {'content': content, 'categories': categories, })


def policy_page(request):
    content = Policy.objects.latest('id')
    categories = Category.objects.filter(is_active=True)
    return render(request, 'static_pages/policy.html', {'content': content, 'categories': categories, })

static_pages/templates/static_pages/about.html
{% extends 'products/_base.html' %}

{% load static %}

{% block description %}
Healthful Food - интернет-магазин здорового питания, является результатом многолетнего увлечения здоровым питанием.
{% endblock %}

{% block keywords %}
о нас, интернет магазин здорового питания, интернет магазин продуктов
{% endblock %}

{% block title %}
Healthful food | О нас
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="tittle text-center">
                <h2>О нас</h2>
            </div>
            <div class="breadcrumbs text-center">
                <a href="{% url 'products:main_page' %}">Главная</a>
                <span>  /  </span>
                <span>О нас</span>
            </div>
            <div class="content">
                {{ content.content|safe }}
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <div>
                        <img src="{% static 'static_pages/icons/delivery.png' %}" alt="delivery" class="img-responsive" height="50">
                    </div>
                    <strong>ДОСТАВИМ ВОВРЕМЯ</strong>
                    <div>
                        Время, место и стоимость доставки определяете вы!
                    </div>
                </div>
                <div class="col-md-4">
                    <div>
                        <img src="{% static 'static_pages/icons/guarante.png' %}" alt="guarantee" class="img-responsive" height="50">
                    </div>
                    <strong>100% КАЧЕСТВО ПРОДУКТОВ</strong>
                    <div>Вся продукция сертифицирована и подвергается жесткому контролю.</div>
                </div>
                <div class="col-md-4">
                    <div>
                        <img src="{% static 'static_pages/icons/ok.png' %}" alt="ok" class="img-responsive" height="50">
                    </div>
                    <strong>СУПЕР-ГАРАНТИЯ</strong>
                    <div>
                        Только у нас возврат в течение 15 дней! По первому требованию мы вернем деньги!
                    </div>
                </div>
            </div>
            <hr>
            <h4 class="text-center">Мы всегда открыты для диалога, а безупречное качество сервиса — наш главный приоритет.</h4>
        </div>
    </section>
{% endblock %}

static_pages/templates/static_pages/contacts.html
{% extends 'products/_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block description %}
Наш адрес МО, г.о. Балашиха мкр. Железнодорожный, ул. Пролетарская 7, email - info@healthfulfood.ru
{% endblock %}

{% block keywords %}
интернет-магазин Healthful food контакты телефон адрес
{% endblock %}

{% block title %}
Healthful food | Контакты
{% endblock %}

{% block content %}
    <section class="contacts">
        <div class="container">
            <div class="tittle text-center">
                <h2>Контакты</h2>
            </div>
            <div class="breadcrumbs text-center">
                <a href="{% url 'products:main_page' %}">Главная</a>
                <span>  /  </span>
                <span>Контакты</span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="contact-form">
						<div class="contact-title">
							<h2>Контактная информация</h2>
						</div>
                        <div class="col-md-12 contact-info">
                            <ul>
                                <li>
                                    <div class="img-icon">
                                        <img src="{% static 'static_pages/icons/contact-place.jpg' %}" alt="phone-icon">
                                    </div>
                                    <strong>Наш адрес</strong>
                                    <br/> {{ contacts.address }}
                                </li>
                                <li>
                                    <div class="img-icon">
                                        <img src="{% static 'static_pages/icons/contact-phone.jpg' %}" alt="phone-icon">
                                    </div>
                                    <strong>Телефон</strong>
                                    <br/> {{ contacts.phone }}
                                </li>
                                <li>
                                    <div class="img-icon">
                                        <img src="{% static 'static_pages/icons/contact-mail.jpg' %}" alt="phone-icon">
                                    </div>
                                    <strong>Email</strong>
                                    <br/> {{ contacts.email }}
                                </li>
                            </ul>
                            <p>{{ contacts.content|safe }}</p>
        {#						<div class="f-sicon2">#}
        {#							<ul>#}
        {#								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>#}
        {#								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>#}
        {#								<li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>#}
        {#								<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>#}
        {#								<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>#}
        {#								<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>#}
        {#							</ul>#}
        {#						</div>#}
                        </div>
					</div>
                </div>
                <div class="col-md-6">
                    <div class="contact-form">
						<div class="contact-title">
							<h2>Задать вопрос</h2>
						</div>
                        <div class="col-md-12 contact-info">
                            {% if form is not Null %}
                            <form method="post" action="{% url 'static_pages:add_question_view' %}" class="order-form">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="id_name" class="required">Ваше имя</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="id_phone_number" class="required">Ваш e-mail</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_comment" class="required">Ваш вопрос</label>
                                    {{ form.question }}
                                </div>
                                <button type="submit" class="add-to-cart2">Отправить</button>
                            </form>
                            {% elif m is not null %}
                                <p>
                                    Спасибо за ваш вопрос!<br>
                                    В ближайшее время администратор рассмотрит ваш вопрос и ответит на вашу почту.
                                </p>
                            {% endif %}
                        </div>
					</div>
                </div>
            </div>
        </div>
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A909647492f3c3a32580a143a9beb670e0a44c5aa58e3f39aed4641bbbf8f76eb&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
    </section>
{% endblock %}

static_pages/templates/static_pages/delivery.html
{% extends 'products/_base.html' %}

{% load static %}

{% block description %}
Вы можете заказать продукты здорового питания с доставкой на дом в Балашихе и Железнодорожном в интернет-магазине Healthful Food.
{% endblock %}

{% block keywords %}
продукты питания, заказать продукты здорового питания, доставка в Балашихе и Железнодорожном
{% endblock %}

{% block title %}
Healthful food | Доставка и оплата
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="tittle text-center">
                <h2>Доставка и оплата</h2>
            </div>
            <div class="breadcrumbs text-center">
                <a href="{% url 'products:main_page' %}">Главная</a>
                <span>  /  </span>
                <span>Доставка и оплата</span>
            </div>
            <div class="content">
                {{ content.content|safe }}
            </div>
        </div>
    </section>
{% endblock %}

static_pages/templates/static_pages/policy.html
{% extends 'products/_base.html' %}

{% load static %}

{% block title %}
Healthful food | Политика обработки персональных данных
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="tittle text-center">
                <h2>Политика обработки персональных данных</h2>
            </div>
            <div class="breadcrumbs text-center">
                <a href="{% url 'products:main_page' %}">Главная</a>
                <span>  /  </span>
                <span>Политика обработки персональных данных</span>
            </div>
            <div class="content">
                {{ content.content|safe }}
            </div>
        </div>
    </section>
{% endblock %}