api/urls.py
from django.urls import path
from api.views import *

app_name = "api"


urlpatterns = [
    path('sale_products/', SaleProductsViewSet.as_view(), name='sale_products'),
    path('new_products/', NewProductsViewSet.as_view(), name='new_products'),
    path('product/<int:pk>', ProductViewSet.as_view(), name='product'),
    path('categories/', CategoriesViewSet.as_view(), name='categories'),
    path('categories/<int:pk>', CategoriesProductViewSet.as_view(), name='categories_products'),
    path('order/create', CreateOrderViewSet.as_view(), name='create_order'),
    # path('order/<int:pk>', OrderViewSet.as_view(), name='order'),
    path('order/<int:id>/<int:pk>', OrderViewSet.as_view(), name='order'),
    # path('orders/', OrdersViewSet.as_view(), name='orders'),
    path('orders/<int:id>', OrdersViewSet.as_view(), name='orders'),
    path('reviews/<int:pk>', ReviewViewSet.as_view(), name='reviews'),
    # path('profile/me', ProfileViewSet.as_view(), name='profile'),
    path('profile/<int:id>', ProfileViewSet.as_view(), name='profile'),
    # path('cart/', CartViewSet.as_view(), name='cart'),
    path('cart/<int:id>', CartViewSet.as_view(), name='cart'),
    # path('cart/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/<int:id>/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/add', CartItemAddViewSet.as_view(), name='cart_item_add'),
    path('profile/create', ProfileCreateViewSet.as_view(), name='profile_create'),
    path('fcm/delete/<int:pk>', DeleteDeviceToken.as_view(), name='device_delete'),

    path('auth', AuthViewSet.as_view(), name='auth'),
]

cart/urls.py
from django.urls import path
from .views import *


app_name = "cart"


urlpatterns = [
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

orders/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = "orders"


urlpatterns = [
    path('create/', order_create, name='order_create'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "products"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('product/<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('category/<slug:slug>', category_detail, name='category_detail'),
    path('add_review/<int:id>', add_review, name='add_review'),
    path('selection/new', selection_new, name='selection_new'),
    path('selection/sale', selection_sale, name='selection_sale'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.functional import curry
from django.views.defaults import permission_denied, page_not_found, server_error

handler403 = curry(permission_denied, exception=Exception('Permission Denied'), template_name='products/errors/403.html')
handler404 = curry(page_not_found, exception=Exception('Page not Found'), template_name='products/errors/404.html')
handler500 = curry(server_error, template_name='products/errors/500.html')


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('products.urls', namespace='products')),
    path('', include('account.urls', namespace='account')),
    path('', include('static_pages.urls', namespace='static_pages')),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('tinymce/', include('tinymce.urls')),
    path('fcm/', include('fcm.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('403', handler403),
        path('404', handler404),
        path('500', handler500),
    ]

orders/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from fcm.utils import get_device_model
from pyfcm import FCMNotification

from products.models import Product
from project import settings


class Status(models.Model):
    name = models.CharField(verbose_name='Статус', max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Order(models.Model):
    # PAY_CHOICES = (
    #     ('Кредитной картой', 'Кредитной картой'),
    #     ('Наличными', 'Наличными')
    # )

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, default='',
                             blank=True, null=True)
    first_name = models.CharField(verbose_name='Имя', max_length=50)
    last_name = models.CharField(verbose_name='Фамилия', max_length=50, blank=True, default='')
    phone_number = models.CharField(verbose_name='Телефон', max_length=20)
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(verbose_name='Адрес', max_length=250, blank=True)
    comment = models.TextField(verbose_name='Комментарий', default='', blank=True)
    # pay_method = models.CharField(verbose_name='Способ оплаты', max_length=20, default='', choices=PAY_CHOICES)
    pay_method = models.CharField(verbose_name='Способ оплаты', max_length=20, default='Наличными', blank=True)
    status = models.ForeignKey(Status, verbose_name='Статус заказа', on_delete=models.CASCADE, default='')
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)
    paid = models.BooleanField(verbose_name='Оплачен', default=False)
    total_price = models.DecimalField(verbose_name='Сумма', max_digits=10, decimal_places=2, blank=True, null=True)
    # __original_mode = 'Новый'

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    # def __init__(self, *args, **kwargs):
    #     super(Order, self).__init__(*args, **kwargs)
    #     self.__original_mode = self.status

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    # def save(self, force_insert=False, force_update=False, *args, **kwargs):
    #     if self.status != self.__original_mode:
    #         change_status(self.status, self.id, self.user_id)
    #
    #     super(Order, self).save(force_insert, force_update, *args, **kwargs)
    #     self.__original_mode = self.status


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2, blank=True, null=True)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)
    total_price = models.DecimalField(verbose_name='Сумма', max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


@receiver(pre_save, sender=OrderItem)
def set_price_to_item(sender, instance, **kwargs):
    instance.price = instance.product.get_price()
    instance.total_price = instance.get_cost()


@receiver(post_save, sender=OrderItem)
def set_total_price_to_order(sender, instance, **kwargs):
    instance.order.total_price = instance.order.get_total_cost()
    instance.order.save()


# def change_status(new_status, order_id, user_id):
@receiver(pre_save, sender=Order)
def change_status(sender, instance, **kwargs):
    try:
        order = Order.objects.get(id=instance.id)
    except Order.DoesNotExist:
        order = None
    if order is not None:
        if instance.status != order.status:
            server_key = settings.FCM_APIKEY
            message_title = "Заказ №" + str(instance.id)
            message_body = "Статус заказа изменен на: " + str(instance.status)
            device = get_device_model()
            try:
                my_phone = device.objects.get(dev_id=instance.user_id)
                reg_id = my_phone.reg_id
                FCMNotification(api_key=server_key).notify_single_device(registration_id=reg_id,
                                                                         message_title=message_title,
                                                                         message_body=message_body)
            except device.DoesNotExist:
                pass

    # FCMNotification(api_key=server_key).notify_single_device(registration_id=reg_id2, message_body=message_body, data_message=data_message)

orders/forms.py
from django import forms
from .models import Order


# CHOICES = [('credit', 'Банковская карта'),
#            ('cash', 'Наличные')]


class OrderCreateForm(forms.ModelForm):
    PAY_CHOICES = (
        ('Кредитной картой', 'Кредитной картой'),
        ('Наличными', 'Наличными')
    )

    class Meta:
        model = Order
        exclude = ['user', 'status', 'created', 'updated', 'paid', 'total_price']

    pay_method = forms.ChoiceField(choices=PAY_CHOICES, widget=forms.RadioSelect())

    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['pay_method'].widget.attrs.update({'class': 'custom-control-input'})

orders/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse

from .models import OrderItem, Status
from .forms import OrderCreateForm
from cart.cart import Cart
from .send_mail import send


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user

            order.status = Status.objects.all()[:1].get()
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],
                                         price=item['product'].get_price(),
                                         quantity=item['quantity'])
            cart.clear()
            items = OrderItem.objects.filter(order=order.id)
            send(order, items)
            if order.pay_method != 'Наличными':
                request.session['order_id'] = order.id
                return redirect('payment:process')
            else:
                return render(request, 'orders/order/created.html', {'order': order, })

    if request.user.is_authenticated:
        data = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'phone_number': request.user.profile.phone_number,
            'address': request.user.profile.address,
        }
        form = OrderCreateForm(initial=data)
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart,
                                                        'form': form, })

orders/templates/orders/order/create.html
{% extends 'products/_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block script %}
    <script src="{% static 'products/scripts/maskedinput.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="inner-header">
    <h1>Оформление заказа</h1>
    <div class="breadcrumbs text-center">
        <a href="{% url 'products:main_page' %}">Главная</a>
        <span>  /  </span>
         <a href="{% url 'cart:cart_detail' %}">Корзина</a>
        <span>  /  </span>
        <span>Оформление заказа</span>
    </div>
</div>
<section class="order">
    <div class="container">
        <form class="order-form" action="." method="post">
            {% csrf_token %}
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                1. Контактные данные
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="id_name" class="col-sm-2 col-form-label required">Имя</label>
                                <div class="col-sm-10">
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_name" class="col-sm-2 col-form-label">Фамилия</label>
                                <div class="col-sm-10">
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_phone_number" class="col-sm-2 col-form-label required">Телефон</label>
                                <div class="col-sm-10">
                                    {{ form.phone_number }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_mail" class="col-sm-2 col-form-label required">Email</label>
                                <div class="col-sm-10">
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_address" class="col-sm-2 col-form-label required">Адрес</label>
                                <div class="col-sm-10">
                                    {{ form.address }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_comment" class="col-sm-2 col-form-label">Комментарий</label>
                                <div class="col-sm-10">
                                    {{ form.comment }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed required" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                2. Способ оплаты
                            </button>
                        </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shipping-outer">
                                {% for radio in form.pay_method %}
                                    <div class="custom-control custom-radio">
                                        {{ radio.tag }}
                                        <label for="{{ radio.id_for_label }}" class="custom-control-label">{{ radio.choice_label }}</label>
                                     </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseTwo">
                                2. Ваш заказ
                            </button>
                        </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body shopping-cart table-responsive-sm">
                            <table class="data-table linearize-table checkout-review-table">
                                <thead>
                                    <tr class="first last">
                                        <th rowspan="1">Продукт</th>
                                        <th colspan="1" class="text-center">Цена</th>
                                        <th rowspan="1" class="text-center">Количество</th>
                                        <th colspan="1" class="text-center">Сумма</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                    {% with product=item.product %}
                                    <tr class="first last odd">
                                        <td class="text-left">
                                            <h3 class="product-name">{{ product.name }}</h3>
                                        </td>
                                        <td class="text-center" data-rwd-label="Price">
                                            <span class="cart-price">
                                         <span class="price">{{ item.price }} &#8381</span>
                                            </span>
                                        </td>
                                        <td class="text-center" data-rwd-label="Qty">{{ item.quantity }}</td>
                                        <td class="a-right last" data-rwd-label="Subtotal">
                                            <span class="cart-price">
                                         <span class="price">{{ item.total_price }} &#8381</span>
                                            </span>
                                        </td>
                                    </tr>
                                    {% endwith %}
                                    {% endfor %}
                                    <tr class="first">
                                        <td style="" class="text-left" colspan="3">
                                            Всего
                                        </td>
                                        <td style="" class="a-right last">
                                            <span class="price">{{ cart.get_total_price }} &#8381</span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="send">
                <input type="submit" value="Оформить" class="add-to-cart2">
            </div>
            <div class="back-to-cart">
                <a href="{% url 'cart:cart_detail' %}">Назад в корзину</a>
            </div>
        </form>
    </div>
    <script>
        $("#id_phone_number").mask("+7(999)999-99-99",{autoclear: false, placeholder:" "});
    </script>
</section>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'products/_base.html' %}

{% block title %}
  Спасибо за заказ
{% endblock %}

{% block content %}
    <div class="container">
        <div class="thnx">
            <div class="text-center">
                <h1 >Спасибо, ваш заказ оформлен</h1>
            </div>
            <p>Письмо-подтверждение отправлено на ваш e-mail: {{ order.email }}</p>
            <p><strong>Номер вашего заказа: </strong>{{ order.id }}</p>
            <p><strong>Дата создания: </strong>{{ order.created }}</p>
            <div class="text-center" style="width: 100%">
                <a href="{% url 'products:main_page' %}" class="add-to-cart2">Продолжить покупки</a>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/email.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  </head>
  <body>
    <span class="preheader">Спасибо за ваш заказ!</span>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <p>Ваш заказ №{{ order.id }} от {{ order.created }}</p>
      </tr>
        <tr>Имя: {{ order.first_name }}</tr>
        <tr>E-mail: {{ order.email }}</tr>
        <tr>Телефон: {{ order.phone_number }}</tr>
        <tr>Сумма заказа: {{ order.total_price }}</tr>
        <br>
        <tr>В ближайшее время с вами свяжется наш сотрудник для подтверждения заказа</tr>
        <br><br><br>
        <tr>Healthful Food</tr>
    </table>
  </body>
</html>