account/urls.py
from django.urls import path
from .views import *

app_name = "account"

urlpatterns = [
    path('account/data', account_data, name='account_data'),
    path('account/orders', account_orders, name='account_orders'),
    path('account/active_orders', account_orders_active, name='account_orders_active'),
    path('registration/', registration_view, name='registration_view'),
    path('update/', update_profile, name='update_profile'),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('order/<int:order_id>', order_desc_view, name='order_desc_view'),
]

api/urls.py
from django.urls import path
from api.views import *

app_name = "api"


urlpatterns = [
    path('sale_products/', SaleProductsViewSet.as_view(), name='sale_products'),
    path('new_products/', NewProductsViewSet.as_view(), name='new_products'),
    path('product/<int:pk>', ProductViewSet.as_view(), name='product'),
    path('categories/', CategoriesViewSet.as_view(), name='categories'),
    path('categories/<int:pk>', CategoriesProductViewSet.as_view(), name='categories_products'),
    path('order/create', CreateOrderViewSet.as_view(), name='create_order'),
    # path('order/<int:pk>', OrderViewSet.as_view(), name='order'),
    path('order/<int:id>/<int:pk>', OrderViewSet.as_view(), name='order'),
    # path('orders/', OrdersViewSet.as_view(), name='orders'),
    path('orders/<int:id>', OrdersViewSet.as_view(), name='orders'),
    path('reviews/<int:pk>', ReviewViewSet.as_view(), name='reviews'),
    # path('profile/me', ProfileViewSet.as_view(), name='profile'),
    path('profile/<int:id>', ProfileViewSet.as_view(), name='profile'),
    # path('cart/', CartViewSet.as_view(), name='cart'),
    path('cart/<int:id>', CartViewSet.as_view(), name='cart'),
    # path('cart/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/<int:id>/<int:pk>', CartItemViewSet.as_view(), name='cart_item'),
    path('cart/add', CartItemAddViewSet.as_view(), name='cart_item_add'),
    path('profile/create', ProfileCreateViewSet.as_view(), name='profile_create'),
    path('fcm/delete/<int:pk>', DeleteDeviceToken.as_view(), name='device_delete'),

    path('auth', AuthViewSet.as_view(), name='auth'),
]

cart/urls.py
from django.urls import path
from .views import *


app_name = "cart"


urlpatterns = [
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
    path('add/<int:product_id>', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

orders/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = "orders"


urlpatterns = [
    path('create/', order_create, name='order_create'),
]

products/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "products"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('product/<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('category/<slug:slug>', category_detail, name='category_detail'),
    path('add_review/<int:id>', add_review, name='add_review'),
    path('selection/new', selection_new, name='selection_new'),
    path('selection/sale', selection_sale, name='selection_sale'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.functional import curry
from django.views.defaults import permission_denied, page_not_found, server_error

handler403 = curry(permission_denied, exception=Exception('Permission Denied'), template_name='products/errors/403.html')
handler404 = curry(page_not_found, exception=Exception('Page not Found'), template_name='products/errors/404.html')
handler500 = curry(server_error, template_name='products/errors/500.html')


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('products.urls', namespace='products')),
    path('', include('account.urls', namespace='account')),
    path('', include('static_pages.urls', namespace='static_pages')),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('tinymce/', include('tinymce.urls')),
    path('fcm/', include('fcm.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('403', handler403),
        path('404', handler404),
        path('500', handler500),
    ]

search/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


app_name = "search"


urlpatterns = [
    path('search', SearchView.as_view(), name='search_view'),
]

products/models.py
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.urls import reverse
import django_filters
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    title = models.CharField(max_length=255, null=True, blank=True, default=None)
    keywords = models.CharField(max_length=255, null=True, blank=True, default=None)
    description_seo = models.TextField(null=True, blank=True, default=None)
    text = HTMLField(verbose_name='Описание')

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('products:category_detail', args=[self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Brand(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Бренд товара'
        verbose_name_plural = 'Бренды товаров'


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class Product(models.Model):
    name = models.CharField(verbose_name='Нвзвание', max_length=64, null=True, default=None)
    article = models.IntegerField(verbose_name='Артикул', default=0)
    slug = models.SlugField(default='', db_index=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2, default=0)
    discount = models.DecimalField(verbose_name='Цена со скидкой', default=0, max_digits=10, decimal_places=2)
    discount_size = models.IntegerField(verbose_name='Скидка', default=0)
    is_new = models.BooleanField(verbose_name='Новинка', default=True)
    category = models.ForeignKey(Category, verbose_name='Категория', null=True, default=None, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, verbose_name='Бренд', null=True, default=None, on_delete=models.CASCADE)
    short_description = HTMLField(verbose_name='Краткое описание')
    description = HTMLField(verbose_name='Полное описание')
    image = models.ImageField(verbose_name='Изображение', upload_to=image_folder, default='')
    is_active = models.BooleanField(verbose_name='Показывать', default=True)
    rating = models.DecimalField(verbose_name='Рейтинг', max_digits=5, decimal_places=2, default=0)
    review_amount = models.IntegerField(verbose_name='Количество отзывов', default=0, blank=True, null=True)
    created = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(verbose_name='Дата обновления', auto_now_add=False, auto_now=True)
    title = models.CharField(max_length=255, null=True, blank=True, default=None)
    keywords = models.CharField(max_length=255, null=True, blank=True, default=None)
    description_seo = models.TextField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.id, self.slug])

    def get_discount(self):
        product = get_object_or_404(Product, id=self.id, is_active=True)
        if product.discount > 0:
            discount_size = round((product.price - product.discount) / (product.price / 100), 0)
        else:
            discount_size = 0
        return discount_size

    def get_price(self):
        return self.discount if self.discount != 0 else self.price

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    product = models.ForeignKey(Product, verbose_name='Продукт', default=None, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=255, default=None, null=True)
    email = models.EmailField(default=None)
    rating = models.IntegerField(verbose_name='Рейтинг', default='5')
    short_desc = models.CharField(verbose_name='Мнение о товаре в одном предложение', max_length=255, default='')
    body = models.TextField(verbose_name='Обзор', default='')
    verificated = models.BooleanField(default=False, verbose_name='Показывать на сайте')
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'

    def __unicode__(self):
        return u'%s' % self.name


@receiver(post_save, sender=Review)
def set_review(sender, instance, **kwargs):
    reviews_sum = Review.objects.filter(product__name=instance.product.name, verificated=True).aggregate(Sum('rating'))
    if reviews_sum['rating__sum'] is not None:
        set_rating(instance)


@receiver(post_delete, sender=Review)
def delete_review(sender, instance, **kwargs):
    reviews_sum = Review.objects.filter(product__name=instance.product.name, verificated=True).aggregate(Sum('rating'))
    if reviews_sum['rating__sum'] is not None:
        set_rating(instance)
    else:
        instance.product.rating = 0
        instance.product.review_amount = 0
        instance.product.save()


def set_rating(instance):
    reviews_sum = Review.objects.filter(product__name=instance.product.name, verificated=True).aggregate(Sum('rating'))
    reviews_count = Review.objects.filter(product__name=instance.product.name, verificated=True).count()
    reviews_rating = round(reviews_sum['rating__sum'] / reviews_count, 1)
    instance.product.rating = reviews_rating
    instance.product.review_amount = reviews_count
    instance.product.save()

products/forms.py
from django import forms
from .models import Review


class AddReviewForm(forms.ModelForm):
    RATING_CHOICES = (
        (5, '1'),
        (4, '2'),
        (3, '3'),
        (2, '4'),
        (1, '5'),
    )

    class Meta:
        model = Review
        exclude = ('product', 'created')

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.RadioSelect(attrs={
        'class': 'star-rating__input'
    }))
    short_desc = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Пример: Очень доволен покупкой',
        'class': 'form-control'
    }))
    body = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Чем вам понравился/не понравился товар?',
        'class': 'form-control'
    }))

    def __init__(self, *args, **kwargs):
        super(AddReviewForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

products/views.py
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.utils import timezone

from cart.forms import CartAddProductForm
from products.filters import ProductFilter
from products.models import *
from cart.cart import Cart
from slider.models import Slider
from static_pages.models import Contacts
from .forms import AddReviewForm


def main_page(request):
    products_new = Product.objects.filter(is_active=True, is_new=True)[:8]
    products_sale = Product.objects.filter(is_active=True, discount__gt=0)[:8]
    contacts = Contacts.objects.latest('id')
    sliders = Slider.objects.filter(is_active=True)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    context = {
        'products_new': products_new,
        'products_sale': products_sale,
        'cart_product_form': cart_product_form,
        'cart': cart,
        'contacts': contacts,
        'sliders': sliders
    }
    return render(request, 'products/main_part_on_main_page.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, is_active=True)
    products = Product.objects.filter(is_active=True, category=product.category).exclude(id=product.id)
    reviews = Review.objects.filter(product__name=product.name, verificated=True)
    cart_product_form = CartAddProductForm()
    review_form = AddReviewForm()
    cart = Cart(request)
    contacts = Contacts.objects.latest('id')
    context = {
        'products': products,
        'product': product,
        'reviews': reviews,
        'cart_product_form': cart_product_form,
        'review_form': review_form,
        'cart': cart,
        'contacts': contacts,
    }
    return render(request, 'products/product_detail.html', context)


def category_detail(request, slug):
    category = Category.objects.get(slug=slug)

    if request.GET.get('sort') is None:
        sort = 'id'
    else:
        sort = request.GET.get('sort')

    if request.GET.get('type') is None or request.GET.get('type') == 'all':
        products_list = Product.objects.filter(is_active=True, category=category).order_by(sort)
    elif request.GET.get('type') == 'new':
        products_list = Product.objects.filter(is_active=True, category=category, is_new=True).order_by(sort)
    elif request.GET.get('type') == 'sale':
        products_list = Product.objects.filter(is_active=True, category=category, discount__gt=0).order_by(sort)

    paginator = Paginator(products_list, 16)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    contacts = Contacts.objects.latest('id')
    context = {
        'products': products,
        'category': category,
        'cart_product_form': cart_product_form,
        'cart': cart,
        'contacts': contacts,
        # 'filter': filter,
    }
    return render(request, 'products/category_detail.html', context)


def add_review(request, id):
    form = AddReviewForm(request.POST)
    product = get_object_or_404(Product, id=id)
    if form.is_valid():
        review = form.save(commit=False)
        review.product = product
        review.created = timezone.now()
        review.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def selection_new(request):
    products_list = Product.objects.filter(is_active=True, is_new=True)
    paginator = Paginator(products_list, 16)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    title = 'Новинки'
    context = {
        'products': products,
        'title': title
    }
    return render(request, 'products/selection.html', context)


def selection_sale(request):
    products_list = Product.objects.filter(is_active=True, discount__gt=0)
    paginator = Paginator(products_list, 16)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    title = 'Скидки'
    context = {
        'products': products,
        'title': title
    }
    return render(request, 'products/selection.html', context)

products/templates/products/footer.html
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 text-center">
            <div>
                <img src="{% static 'products/media/icons/new_logo.png' %}" height="50" alt="logo">
            </div>
            <ul>
                <li>
                    <i class="material-icons" style="font-size: 13px">place</i>
                    <strong>Наш адрес:</strong>
                    <span>{{ contacts.address }}</span>
                </li>
                <li>
                    <i class="material-icons" style="font-size: 13px">phone</i>
                    <strong>Телефон</strong>
                    <span>{{ contacts.phone }}</span>
                </li>
                <li>
                    <i class="material-icons" style="font-size: 13px">mail_outline</i>
                    <strong>Email:</strong>
                    <span>{{ contacts.email }}</span>
                </li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 text-center">
            <h4>Информация</h4>
            <ul>
                <li><a href="{% url 'static_pages:about_page' %}">О нас</a></li>
                <li><a href="{% url 'static_pages:delivery_page' %}">Доставка и оплата</a></li>
                <li><a href="{% url 'static_pages:contacts_view' %}">Контакты</a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 text-center">
            <a href='https://play.google.com/store/apps/details?id=com.healthfulfood.maxim.int_shop&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1' target="_blank"><img alt='Доступно в Google Play' style="width: 50%" src='https://play.google.com/intl/en_us/badges/images/generic/ru_badge_web_generic.png'/></a>
        </div>
    </div>
</div>
<div class="copyright">
    <div class="container text-center">
        2019 <a href="#">Healthful Food</a>
        Интернет-магазин здорового питания
    </div>
    </div>
</div>

products/templates/products/navbar.html
{#{% extends 'products/_base.html' %}#}

{% load static %}
{% load crispy_forms_tags %}

{#{% block navbar %}#}
<!-- contacts in top -->
<nav class="navbar navbar-expand-lg contacts-top">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="{% url 'static_pages:about_page' %}">О нас</a></li>
                <li class="nav-item"><a href="{% url 'static_pages:delivery_page' %}">Доставка и оплата</a></li>
                <li class="nav-item"><a href="{% url 'static_pages:contacts_view' %}">Контакты</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <button type="button" class="log-in" data-toggle="modal" data-target="#exampleModalCenter">Войти</button>
                    </li>
                    <li class="nav-item"><a href="{% url 'account:registration_view' %}">Зарегистрироваться</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'account:account_data' %}">Личный кабинет</a></li>
                    <li class="nav-item"><a href="{% url 'account:logout_view' %}">Выйти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- /contacts in top -->
<!-- menu -->
<nav class="navbar navbar-expand-lg" id="nav-fix-top">
    <div class="container">
        <a href="{% url 'products:main_page' %}" class="navbar-brand">
            <img src="{% static 'products/media/icons/new_logo_black.png' %}" height="30" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% for category in categories%}
                <li class="nav-item">
                    <a class="nav-link name-category" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link name-category" href="#" data-toggle="modal" data-target=".popup1" >
                        <img src="{% static 'products/media/icons/search_icon.png' %}" alt="">
                        <span>Поиск</span>
                    </a>
                </li>
                <li class="nav-item dropdown basket-container">
                {% with total_items=cart|length %}
                    <a class="nav-link name-category dropdown-toggle" id="cart" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                        <img src="{% static 'products/media/icons/cart_icon.png' %}" alt="">
                        <span>Корзина </span>
                        (<span id="total-in-cart">{{ total_items }}</span>)
                    </a>
                    <div id="basket">
                    <ul class="dropdown-menu basket-items">
                        {% if total_items > 0 %}
                            <div id="content">
                                {% for item in cart %}
                                {% with product=item.product %}
                                <div class="cart-content">
                                    <div class="row">
                                        <div class="col-sm-4 col-md-4 text-center">
                                            <div class="pro-img">
                                                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                                            </div>
                                        </div>
                                        <div class="col-sm-8 col-md-8">
                                            <div class="pro-text">
                                                <div class="pro-text-desc">
                                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                                    {% if product.discount > 0 %}
                                                        <strong class="price">{{ product.discount }} &#8381</strong>
                                                        <span class="price-old">{{ product.price }} &#8381</span>
                                                    {% else %}
                                                        <strong class="price">{{ product.price }} &#8381</strong>
                                                    {% endif %}
                                                </div>
                                                <div class="pro-text-amount">
                                                    <div class="row">
                                                        <div class="col-sm-8">
                                                            <span>Количество: {{ item.quantity }}</span>
                                                        </div>
                                                        <div class="col-sm-4 text-right">
                                                            <a href="{% url 'cart:cart_remove' product.id %}" id="delete-item" data-id="{{ product.id }}">
                                                                 <span class="red">
                                                                    <i class="fa fa-close" style="font-size:18px"></i>
                                                                </span>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endwith %}
                                {% endfor %}
                            </div>
                            <div class="total-in-basket">
                                <div class="row">
                                    <div class="col-sm-6 col-md-6 text-left">Всего:</div>
                                    <div class="col-sm-6 col-md-6 text-right">
                                        <strong>{{ cart.get_total_price }} &#8381</strong>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'cart:cart_detail' %}" class="cart-btn">Посмотреть корзину</a>
                            <a href="{% url 'orders:order_create' %}" class="cart-btn">Оформить заказ</a>
                        {% else %}
                            <div class="empty-basket">В корзине нет товаров</div>
                        {% endif %}
                    </ul>
                    </div>
                {% endwith %}
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item login-mobile">
                        <button type="button" class="log-in" data-toggle="modal" data-target="#exampleModalCenter">Войти</button>
                    </li>
                    <li class="nav-item login-mobile"><a href="{% url 'account:registration_view' %}">Зарегистрироваться</a></li>
                {% else %}
                    <li class="nav-item login-mobile"><a href="{% url 'account:account_data' %}">Личный кабинет</a></li>
                    <li class="nav-item login-mobile"><a href="{% url 'account:logout_view' %}">Выйти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- search-popup -->
<div class="modal fade bs-example-modal-lg search-bg popup1" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content search-popup">
            <div class="text-center">
                <a href="#" class="close2" data-dismiss="modal" aria-label="Close">× закрыть</a>
            </div>
            <div class="search-outer">
                <form action="{% url 'search:search_view' %}" method="GET">
                    <div class="row">
                        <div class="col-md-11">
                            <input type="text" placeholder="Поиск товаров..." name="q"/>
                        </div>
                        <div class="col-md-1 text-right">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /search-popup -->
<!-- /.menu -->
<script>
    $(document).on('submit', '#login_form', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url 'account:login_view' %}',
            data: {
                username: $("#id_username").val(),
                password: $("#id_password").val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (data) {
                if (data.login) {
                    location.reload();
                }
                else {
                    if (data.error == 'nonactive'){
                        var text = 'Данный аккаунт больше не активен';
                    }
                    else {
                        var text = 'Неправильный логин или пароль!';
                    }
                    $('.error').removeClass('d-none');
                    $('.error span').text(text);
                }
            }
        });
    });
    $(document).on('click', '#delete-item', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var url = $(this).attr('href');
            console.log(url);
            $.ajax({
                type: 'GET',
                url: url,
                data: {
                    product_id: id
                },
                success: function (data) {
                    if (data.success) {
                        $('#total-in-cart').text(data.amount);
                        $('#basket').load(' .basket-items');
                    }
                }
            });
        });
</script>